---
- name: Install and configure Apache with handler
  hosts: n01737472-c-vm-1-n01737472.eastus.cloudapp.azure.com
  become: yes
  tasks:

    - name: Install Apache web server
      apt:
        name: apache2
        state: present
      notify: restart apache

    - name: Add hostname to index.html
      copy:
        content: "Welcome to {{ ansible_hostname }}!"
        dest: /var/www/html/index.html
      notify: restart apache

    - name: Enable Apache to auto-start on boot
      systemd:
        name: apache2
        enabled: yes

  handlers:
    - name: restart apache
      systemd:
        name: apache2
        state: restarted
