---
- name: Install Apache and MariaDB with multiple handlers
  hosts: n01737472-c-vm-2-n01737472.eastus.cloudapp.azure.com
  become: yes
  tasks:

    - name: Install Apache web server
      apt:
        name: apache2
        state: present
      notify: restart apache

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present
      notify: restart mariadb

    - name: Enable Apache to auto-start on boot
      systemd:
        name: apache2
        enabled: yes

    - name: Enable MariaDB to auto-start on boot
      systemd:
        name: mariadb
        enabled: yes

  handlers:
    - name: restart apache
      systemd:
        name: apache2
        state: restarted

    - name: restart mariadb
      systemd:
        name: mariadb
        state: restarted
