- name: Create user, group, and install apache/nmap
  hosts: linux
  become: true
  tasks:
    - name: Create group cloudadmins
      group:
        name: cloudadmins
        gid: 3000

    - name: Create user user4000
      user:
        name: user4000
        uid: 5000
        group: cloudadmins

    - name: Install apache2
      apt:
        name: apache2
        state: latest
        update_cache: true

    - name: Install nmap
      apt:
        name: nmap
        state: latest
    - name: Ensure apache2 is started and enabled
      service:
        name: apache2
        state: started
        enabled: true